language: java

sudo: false # For faster builds

os: linux

dist: xenial  # Ubuntu

jdk:
  - openjdk11

branches:
  only:
  - master

environments:
  - AWS_ACCESS_KEY_ID = ${AWS_ACCESS_KEY_ID}
  - AWS_SECRET_ACCESS_KEY = ${AWS_SECRET_ACCESS_KEY}

install:
  - pip install -- user awscli
  - pip install --user aws-sam-cli

script:
  - sam validate
  - sam build

deploy:
  provider: script
  script: sam deploy --no-confirm-changeset
  skip_cleanup: true
  on:
    branch: master

