version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Fun fun party time
      - docker --version
  build:
    commands:
      - sam validate
      - sam build

artifacts:
  files:
    template.yaml