version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Pre-Build
      - sudo sam local start-api
  build:
    commands:
      - echo Build
      - sam build

artifacts:
  files:
    template.yaml