version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - docker --version
  build:
    commands:
      - sam build

artifacts:
  files:
    template.yaml