AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Lambda function for student-service

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Resources:
  StudentServiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      ImageUri: "studentservicefunction:java11-maven-v1"
      PackageType: "Image"
      Events:
        CreateStudent:
          Type: Api
          Properties:
            Path: /v1/students/{id}
            Method: post
        ReadStudent:
          Type: Api
          Properties:
            Path: /v1/students/{id}
            Method: get
        DeleteStudent:
          Type: Api
          Properties:
            Path: /v1/students/{id}
            Method: delete

        UpdateStudent:
          Type: Api
          Properties:
            Path: /v1/students/{id}
            Method: put
    Metadata:
      DockerTag: java11-maven-v1
      DockerContext: ./StudentServiceFunction
      Dockerfile: Dockerfile
