package com.igp.studentservice.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@Builder
@NoArgsConstructor
@DynamoDBTable(tableName = "studentDetailed-table")
public class StudentDetailed {

    @DynamoDBHashKey(attributeName = "studentId")
    @DynamoDBAutoGeneratedKey
    private String studentId;

    @DynamoDBAttribute(attributeName = "basic")
    private StudentBasic basic;

    @DynamoDBAttribute(attributeName = "uni")
    private StudentUni uni;

    public StudentDetailed(StudentBasic studentBasic, StudentUni studentUni) {
        this.basic = studentBasic;
        this.uni = studentUni;
    }

    public StudentBasic getBasic() {
        return basic;
    }

    public StudentUni getUni() {
        return uni;
    }

    public void setBasic(StudentBasic basic) {
        this.basic = basic;
    }

    public void setUni(StudentUni uni) {
        this.uni = uni;
    }

    @Override
    public String toString() {
        return "StudentDetailed{}";
    }
}
