package com.igp.studentservice.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.google.gson.annotations.SerializedName;
import lombok.*;

@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "student-table")
public class Student {

    @DynamoDBHashKey(attributeName = "studentId")
    @DynamoDBAutoGeneratedKey
    private String studentId;

    @DynamoDBAttribute(attributeName = "username")
    private String username;

    @DynamoDBAttribute(attributeName = "email")
    private String email;

    @DynamoDBAttribute(attributeName = "realName")
    @SerializedName("realname")
    private String realName;

    @DynamoDBAttribute(attributeName = "age")
    private Integer age;

    @DynamoDBAttribute(attributeName = "gender")
    private String gender;

    @DynamoDBAttribute(attributeName = "universityName")
    private String universityName;

    @DynamoDBAttribute(attributeName = "universityEmail")
    private String universityEmail;

    @DynamoDBAttribute(attributeName = "year")
    private Integer year;

    @DynamoDBAttribute(attributeName = "course")
    private String course;


}
